#!/usr/bin/env bash

echo "Criando diretórios..." | tee -a "$FILE_LOG"

createDir "/publico"
createDir "/adm"
createDir "/ven"
createDir "/sec"

echo "Criando grupos de usuários..." | tee -a "$FILE_LOG"

createGroup "GRP_ADM"
createGroup "GRP_VEN"
createGroup "GRP_SEC"

echo "Criando usuários..." | tee -a "$FILE_LOG"
createUsers

echo "Especificando permissões do diretórios..." | tee -a "$FILE_LOG"

chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

chmod 770 /adm
chmod 770 /ven
chmod 770 /sec
chmod 770 /publico

echo "Realizando atualizações no sistema..." | tee -a "$FILE_LOG"
updateSystem

echo "Fim..."
